name: Deploy React Application
# When frontend is changed, rebuild react app and deploy to GitHub Pages
on:
  push:
    branches: [ main ]
    paths: [ 'frontend/**' ]

jobs:
  deploy_to_gh_pages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x] 

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci, build and test
        working-directory: ./frontend
        run: |
          npm ci
          npm run build --if-present
      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./frontend/build 
          


